### ISSUE TITLE
Google Sign-In Javascript API Deprecation - Migrate to Google Identity Services

### ISSUE THREAD

**Issue by gernet-eckerd** [ellucian-developer/experience-productivity-extensions#19]
The legacy Google Sign-In API is being turned off by March 21, 2023. The Google authentication piece will need to be migrated to Google Identity Services.

Here's Google's announcement about the deprecation/migration: https://developers.googleblog.com/2022/03/gis-jsweb-authz-migration.html

Affected files:
/src/google/context-providers/google-auth-context-provider.js

**Comment by lylehenderson** [comment]
To add to this:  
Currently not able to deploy new applications because of the deprecated auth.

VM598 google-auth-context-provider.js:126 gapi failed {error: 'idpiframe_initialization_failed', details: 'You have created a new client application that use…i/web/guides/gis-migration) for more information.'}details: "You have created a new client application that uses libraries for user authentication or authorization that will soon be deprecated. New clients must use the new libraries instead; existing clients must also migrate before these libraries are deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information."error: "idpiframe_initialization_failed"[[Prototype]]: Object

**Comment by lylehenderson** [comment]
I'm not able to update the issue.  But Pull Request: https://github.com/ellucian-developer/experience-productivity-extensions/pull/21

Fixed issues for me.

**Comment by lylehenderson** [comment]
Hmm, after further review, the sessions disconnect pretty quick.
The login feature also seems abit counter intuitive, especially at first time login.

Log into SSO, which redirects to Ellucian Experience, prompted to log into gmail, which is the SSO that you originally logged into?  Kinda seems like a cart before the horse issue to me.

**Comment by ellucianBret** [comment]
This issue is resolved in the 1.2.1 release.
